
export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_YOUTUBE_TRAILER_KEYS_PENDING = 'FETCH_YOUTUBE_TRAILER_KEYS_PENDING';
export const FETCH_YOUTUBE_TRAILER_KEYS_SUCCESS = 'FETCH_YOUTUBE_TRAILER_KEYS_SUCESS';
export const FETCH_YOUTUBE_TRAILER_KEYS_ERROR = 'FETCH_YOUTUBE_TRAILER_KEYS_ERROR';
export const CLEAR_TRAILERS = 'CLEAR_TRAILERS';